#!/usr/bin/bash

set -e

gcc -Wall -Wextra -pedantic -O3 -lm -lSDL2 -o ising ising.c
gcc -Wall -Wextra -pedantic -O3 -lm -lSDL2 -o julia julia.c color.h
gcc -Wall -Wextra -pedantic -O3 -lm -lSDL2 -o mandelbrot mandelbrot.c color.h
