#!/usr/bin/bash

set -e

clang -Wall -Wextra -pedantic -O3 -lm -lSDL2 -o ising ising.c
clang -Wall -Wextra -pedantic -O3 -lm -lSDL2 -o julia julia.c
clang -Wall -Wextra -pedantic -O3 -lm -lSDL2 -o mandelbrot mandelbrot.c
